
CC=/usr/bin/gcc

CFLAGS= -std=iso9899:1999 -m64 -g -O0 -fno-builtin \
	-fno-fast-math

CPPFLAGS=-D_TS_ERRNO -D_POSIX_PTHREAD_SEMANTICS -D_LARGEFILE64_SOURCE \
	-D_X_OPEN_SOURCE=600 -D_REENTRANT

LIBS = -lpthread -lrt -lm

OBJQ = sysmem.o sysinfo.o q_work.o enqueue.o dequeue.o q_create.o \
	q_destroy.o do_work.o fibber.o

%.o: %.c
	$(CC) -c -o $@ $< $(CFLAGS) $(CPPFLAGS)

q_work: $(OBJQ)
	$(CC) -o $@ $^ -L$(LDIR) $(CFLAGS) $(CPPFLAGS) -D_REENTRANT $(LIBS)

clean:
	rm -f *.o q_work
