
IDIR=/opt/bw/include
CC=/usr/bin/cc
LDIR=/opt/bw/lib

CFLAGS= -I$(IDIR) -std=iso9899:1999 -m64 -g -O0 \
	-fno-fast-math -fno-builtin -Wl,-rpath=/opt/bw/lib

CPPFLAGS=-D_TS_ERRNO -D_POSIX_PTHREAD_SEMANTICS -D_LARGEFILE64_SOURCE \
	-D_X_OPEN_SOURCE=600

LIBS = -lm -lgmp -lmpfr

OBJ = mpfr_ver.o

%.o: %.c
	$(CC) -c -o $@ $< $(CFLAGS) $(CPPFLAGS)

mpfr_ver: $(OBJ)
	$(CC) -o $@ $^ $(CFLAGS) $(CPPFLAGS) -L$(LDIR) $(LIBS)

clean:
	rm -f *.o mpfr_ver
