
IDIR = .

CC=/usr/bin/gcc

CFLAGS= -I$(IDIR) -std=iso9899:1999 -pedantic -fno-builtin -g -m64

CPPFLAGS=-D_TS_ERRNO -D_POSIX_PTHREAD_SEMANTICS -D_LARGEFILE64_SOURCE \
	-D_XOPEN_SOURCE=600

LIBS = -lm

DEPS = v.h
SRCS = $(wildcard c*.c) line_plane_icept.c
OBJS = $(SRCS:.c=.o)

%.o: %.c $(DEPS)
	$(CC) -c -o $@ $< $(CFLAGS) $(CPPFLAGS)

cplex_test: $(OBJS)
	$(CC) -o $@ $^ $(CFLAGS) $(CPPFLAGS) $(LIBS)

clean:
	rm -f $(OBJS) cplex_test
